# On force le scan de tout le dossier Controller
controllers:
    resource: ../src/Controller/
    type: attribute

# Route de secours au cas où les attributs échoueraient
manual_test:
    path: /test-manuel
    controller: App\Controller\Admin\DashboardController::index

app_orders_mark_delivered:
    path: /orders/{id}/mark-delivered
    controller: App\Controller\OrdersController::markAsDelivered
    methods: POST